# Exploratory Data Analysis and Insights on the Automobile Dataset Using Pandas

### Beginner-to-Intermediate Pandas Practice Notebook

This notebook is designed for students who are learning how to clean and explore mixed numerical and categorical data using **Pandas**.

The exercises begin with basic DataFrame operations and gradually introduce:

- Loading a CSV file with custom missing-value markers
- Inspecting rows, columns, and data types
- Finding and handling missing values
- Selecting, filtering, and sorting records
- Exploring vehicle categories
- Calculating descriptive statistics
- Grouping and aggregating data
- Creating derived columns
- Examining correlations
- Creating basic visualizations
- Exporting cleaned data

## About the Dataset

The **Automobile.csv** dataset contains information about **205 automobiles** from the 1985 model year.

It contains **26 columns** describing vehicle specifications, fuel economy, insurance risk, and price.

### Main Column Groups

| Group | Example columns | Description |
|---|---|---|
| Vehicle identity | `make`, `fuel_type`, `body_style` | Manufacturer and vehicle categories |
| Size and weight | `wheel_base`, `length`, `width`, `curb_weight` | Physical measurements and vehicle weight |
| Engine | `engine_type`, `num_cylinders`, `engine_size`, `horsepower` | Engine design and performance information |
| Fuel economy | `city_mpg`, `highway_mpg` | City and highway fuel efficiency |
| Cost and risk | `price`, `symboling`, `normalized_losses` | Vehicle price and insurance-risk information |

### Important Observation

The original dataset uses a question mark (`?`) to represent missing information. When loading the CSV, use the `na_values` parameter so Pandas treats these markers as missing values.

The original hyphenated field names were converted to lowercase names with underscores to make them easier to use in Python.

**Source:** [UCI Machine Learning Repository](https://archive.ics.uci.edu/dataset/10/automobile)  
**License:** CC BY 4.0

## Learning Goal

By completing this assignment, you will practice a complete beginner-to-intermediate data-cleaning and exploration workflow. You will work with missing values, compare vehicle groups, calculate useful derived measures, and summarize the relationships between price, performance, and fuel economy.

## 1. Loading and Understanding the Dataset

### Question 1
Import the Pandas library using the alias `pd` and read **Automobile.csv** into a DataFrame named `df`. Use `na_values='?'` so question marks are treated as missing values.

In [1]:
import pandas as pd 
path = r"C:\Users\SD\Downloads\Automobile.csv"
df = pd.read_csv(path)

### Question 2
Display the first **5 rows** of the dataset.

In [2]:
df.head(5)

,symboling,normalized_losses,make,fuel_type,aspiration,num_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

### Question 3
Display the last **5 rows** of the dataset.

In [3]:
df.tail

<bound method NDFrame.tail of      symboling normalized_losses         make fuel_type aspiration num_doors  \
0            3                 ?  alfa-romero       gas        std       two
1            3                 ?  alfa-romero       gas        std       two
2            1                 ?  alfa-romero       gas        std       two
3            2               164         audi       gas        std      four
4            2               164         audi       gas        std      four
..         ...               ...          ...       ...        ...       ...
200         -1                95        volvo       gas        std      four
201         -1                95        volvo       gas      turbo      four
202         -1                95        volvo       gas        std      four
203         -1                95        volvo    diesel      turbo      four
204         -1                95        volvo       gas      turbo      four

      body_style drive_wheels engine_location  wheel_base  ...  engine_size  \
0    convertible          rwd           front        88.6  ...          130
1    convertible          rwd           front        88.6  ...          130
2      hatchback          rwd           front        94.5  ...          152
3          sedan          fwd           front        99.8  ...          109
4          sedan          4wd           front        99.4  ...          136
..           ...          ...             ...         ...  ...          ...
200        sedan          rwd           front       109.1  ...          141
201        sedan          rwd           front       109.1  ...          141
202        sedan          rwd           front       109.1  ...          173
203        sedan          rwd           front       109.1  ...          145
204        sedan          rwd           front       109.1  ...          141

     fuel_system  bore  stroke compression_ratio horsepower  peak_rpm  \
0           mpfi  3.47    2.68               9.0        111      5000
1           mpfi  3.47    2.68               9.0        111      5000
2           mpfi  2.68    3.47               9.0        154      5000
3           mpfi  3.19    3.40              10.0        102      5500
4           mpfi  3.19    3.40               8.0        115      5500
..           ...   ...     ...               ...        ...       ...
200         mpfi  3.78    3.15               9.5        114      5400
201         mpfi  3.78    3.15               8.7        160      5300
202         mpfi  3.58    2.87               8.8        134      5500
203          idi  3.01    3.40              23.0        106      4800
204         mpfi  3.78    3.15               9.5        114      5400

    city_mpg highway_mpg  price
0         21          27  13495
1         21          27  16500
2         19          26  16500
3         24          30  13950
4         18          22  17450
..       ...         ...    ...
200       23          28  16845
201       19          25  19045
202       18          23  21485
203       26          27  22470
204       19          25  22625

[205 rows x 26 columns]>

### Question 4
Find the total number of **rows and columns** in the dataset.

In [5]:
df.shape

(205, 26)

### Question 5
Display all the **column names** in the dataset.

In [6]:
df.columns

Index(['symboling', 'normalized_losses', 'make', 'fuel_type', 'aspiration',
       'num_doors', 'body_style', 'drive_wheels', 'engine_location',
       'wheel_base', 'length', 'width', 'height', 'curb_weight', 'engine_type',
       'num_cylinders', 'engine_size', 'fuel_system', 'bore', 'stroke',
       'compression_ratio', 'horsepower', 'peak_rpm', 'city_mpg',
       'highway_mpg', 'price'],
      dtype='str')

### Question 6
Display the **data type of each column**.

In [7]:
df.dtypes

symboling              int64
normalized_losses        str
make                     str
fuel_type                str
aspiration               str
num_doors                str
body_style               str
drive_wheels             str
engine_location          str
wheel_base           float64
length               float64
width                float64
height               float64
curb_weight            int64
engine_type              str
num_cylinders            str
engine_size            int64
fuel_system              str
bore                     str
stroke                   str
compression_ratio    float64
horsepower               str
peak_rpm                 str
city_mpg               int64
highway_mpg            int64
price                    str
dtype: object

### Question 7
Display a complete summary of the DataFrame using `info()`.

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized_losses  205 non-null    str
 2   make               205 non-null    str
 3   fuel_type          205 non-null    str
 4   aspiration         205 non-null    str
 5   num_doors          205 non-null    str
 6   body_style         205 non-null    str
 7   drive_wheels       205 non-null    str
 8   engine_location    205 non-null    str
 9   wheel_base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb_weight        205 non-null    int64
 14  engine_type        205 non-null    str
 15  num_cylinders      205 non-null    str
 16  engine_size        205 non-null    int64
 17  fuel_system        205 non-null    str
 18  bore               205 non-null    str
 19  stroke             205 non-null    str
 20  compression_ratio  205 non-null    float64
 21  horsepower         205 non-null    str
 22  peak_rpm           205 non-null    str
 23  city_mpg           205 non-null    int64
 24  highway_mpg        205 non-null    int64
 25  price              205 non-null    str
dtypes: float64(5), int64(5), str(16)
memory usage: 41.8 KB

## 2. Checking and Handling Missing Values

### Question 8
Display the number of **missing values in each column**.

In [9]:
df.isnull().sum()

symboling            0
normalized_losses    0
make                 0
fuel_type            0
aspiration           0
num_doors            0
body_style           0
drive_wheels         0
engine_location      0
wheel_base           0
length               0
width                0
height               0
curb_weight          0
engine_type          0
num_cylinders        0
engine_size          0
fuel_system          0
bore                 0
stroke               0
compression_ratio    0
horsepower           0
peak_rpm             0
city_mpg             0
highway_mpg          0
price                0
dtype: int64

### Question 9
Display only the columns that contain **at least one missing value**.
`

In [1]:
df.isna().sum()

NameError: name 'df' is not defined

### Question 10
Calculate the **total number of missing values** in the entire DataFrame.

In [ ]:
df.isnull().

AttributeError: 'DataFrame' object has no attribute 'total'

### Question 11
Display all rows where the **price** is missing.

### Question 12
Create a DataFrame named `df_clean` by removing rows with missing values in `price` or `horsepower`. Display its shape.

In [18]:
df_clean = df.dropna(subset=['price', 'horsepower'])
print(df_clean.shape)

(205, 26)

## 3. Selecting Rows and Columns

### Question 13
Select and display only the **make** column from `df_clean`.

In [19]:
df_clean['make']

0      alfa-romero
1      alfa-romero
2      alfa-romero
3             audi
4             audi
          ...
200          volvo
201          volvo
202          volvo
203          volvo
204          volvo
Name: make, Length: 205, dtype: str

### Question 14
Select and display the **make, body_style, horsepower, city_mpg, and price** columns.

### Question 15
Using `iloc`, display the first **5 rows and first 6 columns** of `df_clean`.

In [23]:
df_clean.iloc[0:5,0:6]

   symboling normalized_losses         make fuel_type aspiration num_doors
0          3                 ?  alfa-romero       gas        std       two
1          3                 ?  alfa-romero       gas        std       two
2          1                 ?  alfa-romero       gas        std       two
3          2               164         audi       gas        std      four
4          2               164         audi       gas        std      four

### Question 16
Using `loc`, display rows **10 to 15** for the columns **make, engine_size, horsepower, and price**.

In [24]:
df.loc[10:15,['make','engine_size','horsepower','price']]

   make  engine_size horsepower  price
10  bmw          108        101  16430
11  bmw          108        101  16925
12  bmw          164        121  20970
13  bmw          164        121  21105
14  bmw          164        121  24565
15  bmw          209        182  30760

## 4. Exploring Categories and Descriptive Statistics

### Question 17
Display all the **unique automobile manufacturers** in the dataset.

In [26]:
df.make.unique()

<StringArray>
[  'alfa-romero',          'audi',           'bmw',     'chevrolet',
         'dodge',         'honda',         'isuzu',        'jaguar',
         'mazda', 'mercedes-benz',       'mercury',    'mitsubishi',
        'nissan',        'peugot',      'plymouth',       'porsche',
       'renault',          'saab',        'subaru',        'toyota',
    'volkswagen',         'volvo']
Length: 22, dtype: str

### Question 18
Count the number of automobiles produced by each manufacturer using `value_counts()`.

In [27]:
df.make.value_counts()

make
toyota           32
nissan           18
mazda            17
honda            13
mitsubishi       13
subaru           12
volkswagen       12
peugot           11
volvo            11
dodge             9
bmw               8
mercedes-benz     8
audi              7
plymouth          7
saab              6
porsche           5
isuzu             4
alfa-romero       3
chevrolet         3
jaguar            3
renault           2
mercury           1
Name: count, dtype: int64

### Question 19
Display all unique **body styles** and count the number of automobiles in each style.

In [ ]:
df['body_style'].unique().

SyntaxError: invalid syntax (2540451831.py, line 1)

### Question 20
Count the values in the **fuel_type** and **aspiration** columns.

### Question 21
Display descriptive statistics for the numeric columns in `df_clean` using `describe()`.

### Question 22
Calculate the **mean price**, **maximum horsepower**, and **minimum city fuel economy**.

## 5. Filtering and Sorting

### Question 23
Display all automobiles whose **price is greater than 20,000**.

### Question 24
Display only automobiles manufactured by **Toyota**.

### Question 25
Display all **sedans** with **city_mpg greater than 25**.

### Question 26
Using `query()`, display automobiles whose **horsepower is greater than 120** and **price is less than 20,000**.

### Question 27
Sort `df_clean` by **price in descending order** and display the first 10 rows.

### Question 28
Display the **5 automobiles with the highest highway_mpg**.

## 6. Grouping and Aggregation

### Question 29
Calculate the **average price for each body style**.

### Question 30
Calculate the **average city_mpg and highway_mpg for each fuel type**.

### Question 31
For each drive-wheel category, calculate the **minimum, maximum, and mean price** using `agg()`.

### Question 32
Create a frequency table showing the number of automobiles for each **body_style and fuel_type** using `pd.crosstab()`.

### Question 33
Determine which manufacturer has the **highest average horsepower** among manufacturers with at least 3 automobiles in `df_clean`.

## 7. Creating and Modifying Columns

### Question 34
Create a new column named **price_category** using `apply()` with a `lambda` function. Store `Expensive` when `price` is greater than or equal to 20,000; otherwise store `Affordable`.

### Question 35
Create a new column named **mpg_difference** by subtracting `city_mpg` from `highway_mpg`.

### Question 36
Create a new column named **power_to_weight** by dividing `horsepower` by `curb_weight`.

## 8. Correlation, Visualization, and Export

### Question 37
Create a correlation matrix for **price, horsepower, engine_size, curb_weight, city_mpg, and highway_mpg**.

### Question 38
Create a **histogram** of automobile prices with an appropriate title and axis labels.

### Question 39
Create a **bar chart** showing the average price for each body style.

### Question 40
Save `df_clean` as **Automobile_Cleaned.csv** using `to_csv()` without saving the index.

## End of Practice

Try to solve each question independently before checking any reference material.

The main goal is to become comfortable with cleaning and analyzing a dataset that contains numerical values, categories, and missing information before moving to predictive modeling.